// Generated by tools/modern-art/register_areas.mjs from the area manifests.
// Do not edit by hand: re-bake the area, then re-run the script.
import type { AuthoredAreaDef } from './authoredAreas';

export const LAZY_AUTHORED_AREAS: AuthoredAreaDef[] = [
  {
    id: 'foundry-arena', mapSeed: 'campaign:01-foundry', rects: [[54,10,69,23]],
    practicals: [
      { x: 120.6, y: 10.2, z: 35, color: [1, 0.5, 0.22], intensity: 34, distance: 26 },
      { x: 123, y: 15, z: 36, color: [0.8, 0.88, 1], intensity: 18, distance: 26 },
    ],
  },
  {
    id: 'foundry-spur', mapSeed: 'campaign:01-foundry', rects: [[22,26,31,34]],
    practicals: [
      { x: 53, y: 6, z: 56, color: [0.85, 0.92, 1], intensity: 16, distance: 16 },
      { x: 53, y: 6, z: 64, color: [0.85, 0.92, 1], intensity: 16, distance: 16 },
    ],
  },
  {
    id: 'gullet-arena', mapSeed: 'campaign:02-gullet', rects: [[59,34,73,46]],
    practicals: [
      { x: 132.5, y: 10.1, z: 80, color: [1, 0.42, 0.3], intensity: 40, distance: 28 },
      { x: 144, y: 12, z: 80, color: [0.72, 0.84, 1], intensity: 22, distance: 30 },
    ],
  },
  {
    id: 'gullet-crop', mapSeed: 'campaign:02-gullet', rects: [[38,6,51,17]],
    practicals: [
      { x: 83, y: 8.2, z: 20, color: [1, 0.5, 0.32], intensity: 26, distance: 22 },
      { x: 94, y: 8.2, z: 27, color: [1, 0.5, 0.32], intensity: 26, distance: 22 },
    ],
  },
  {
    id: 'gullet-start', mapSeed: 'campaign:02-gullet', rects: [[5,7,12,13]],
    practicals: [
      { x: 22.85, y: 6.6, z: 20, color: [1, 0.4, 0.3], intensity: 18, distance: 18 },
    ],
  },
  {
    id: 'catacombs-arena', mapSeed: 'campaign:03-catacombs', rects: [[75,22,88,35]],
    practicals: [
      { x: 150.8, y: 11, z: 57, color: [0.62, 0.74, 0.95], intensity: 18, distance: 26 },
      { x: 175.2, y: 11, z: 57, color: [0.62, 0.74, 0.95], intensity: 18, distance: 26 },
    ],
  },
  {
    id: 'catacombs-crossing', mapSeed: 'campaign:03-catacombs', rects: [[38,38,50,50]],
    practicals: [
      { x: 88, y: 9.5, z: 88, color: [1, 0.68, 0.38], intensity: 30, distance: 24 },
      { x: 88, y: 27.387, z: 88, color: [0.75, 0.82, 0.95], intensity: 14, distance: 26 },
    ],
  },
  {
    id: 'catacombs-start', mapSeed: 'campaign:03-catacombs', rects: [[2,41,9,47]],
    practicals: [
      { x: 17.1, y: 6.1, z: 88, color: [1, 0.66, 0.36], intensity: 16, distance: 18 },
    ],
  },
];
