// Regenerate src/render/authoredAreaList.ts from every baked area manifest
// (art/modern/areas/<id>/manifest.json). Run after baking an area.
import { readdirSync, readFileSync, existsSync, writeFileSync } from 'node:fs';

const root = 'art/modern/areas';
const areas = readdirSync(root).filter(id => existsSync(`${root}/${id}/manifest.json`) && existsSync(`public/modern/areas/${id}/environment.glb`))
  .map(id => JSON.parse(readFileSync(`${root}/${id}/manifest.json`, 'utf8')))
  .sort((a, b) => a.mapSeed.localeCompare(b.mapSeed) || a.id.localeCompare(b.id));
const round = v => Math.round(v * 1000) / 1000;
const body = areas.map(a => `  {
    id: '${a.id}', mapSeed: '${a.mapSeed}', rects: ${JSON.stringify(a.rects)},
    practicals: [
${a.practicals.map(p => `      { x: ${round(p.x)}, y: ${round(p.y)}, z: ${round(p.z)}, color: [${p.color.map(round).join(', ')}], intensity: ${round(p.intensity)}, distance: ${round(p.distance)} },`).join('\n')}
    ],
  },`).join('\n');
writeFileSync('src/render/authoredAreaList.ts', `// Generated by tools/modern-art/register_areas.mjs from the area manifests.
// Do not edit by hand: re-bake the area, then re-run the script.
import type { AuthoredAreaDef } from './authoredAreas';

export const LAZY_AUTHORED_AREAS: AuthoredAreaDef[] = [
${body}
];
`);
console.log(`Registered ${areas.length} areas: ${areas.map(a => a.id).join(', ')}`);
